package br.uff.es2.war.entity;
// Generated 05/09/2014 12:02:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Continente generated by hbm2java
 */
public class Continente  implements java.io.Serializable {


     private Integer codContinente;
     private Mundo mundo;
     private String nome;
     private Set objconqconts = new HashSet(0);
     private Set territorios = new HashSet(0);

    public Continente() {
    }

	
    public Continente(Mundo mundo, String nome) {
        this.mundo = mundo;
        this.nome = nome;
    }
    public Continente(Mundo mundo, String nome, Set objconqconts, Set territorios) {
       this.mundo = mundo;
       this.nome = nome;
       this.objconqconts = objconqconts;
       this.territorios = territorios;
    }
   
    public Integer getCodContinente() {
        return this.codContinente;
    }
    
    public void setCodContinente(Integer codContinente) {
        this.codContinente = codContinente;
    }
    public Mundo getMundo() {
        return this.mundo;
    }
    
    public void setMundo(Mundo mundo) {
        this.mundo = mundo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getObjconqconts() {
        return this.objconqconts;
    }
    
    public void setObjconqconts(Set objconqconts) {
        this.objconqconts = objconqconts;
    }
    public Set getTerritorios() {
        return this.territorios;
    }
    
    public void setTerritorios(Set territorios) {
        this.territorios = territorios;
    }




}


