package br.uff.es2.war.entity;
// Generated 05/09/2014 12:02:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Jogador generated by hbm2java
 */
public class Jogador  implements java.io.Serializable {


     private Integer codJogador;
     private String login;
     private String senha;
     private String email;
     private Set partidas = new HashSet(0);
     private Set historicos = new HashSet(0);
     private Set jogams = new HashSet(0);

    public Jogador() {
    }

	
    public Jogador(String login, String senha, String email) {
        this.login = login;
        this.senha = senha;
        this.email = email;
    }
    public Jogador(String login, String senha, String email, Set partidas, Set historicos, Set jogams) {
       this.login = login;
       this.senha = senha;
       this.email = email;
       this.partidas = partidas;
       this.historicos = historicos;
       this.jogams = jogams;
    }
   
    public Integer getCodJogador() {
        return this.codJogador;
    }
    
    public void setCodJogador(Integer codJogador) {
        this.codJogador = codJogador;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Set partidas) {
        this.partidas = partidas;
    }
    public Set getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Set historicos) {
        this.historicos = historicos;
    }
    public Set getJogams() {
        return this.jogams;
    }
    
    public void setJogams(Set jogams) {
        this.jogams = jogams;
    }




}


