package br.uff.es2.war.entity;
// Generated 05/09/2014 12:02:41 by Hibernate Tools 3.6.0



/**
 * JogamId generated by hbm2java
 */
public class JogamId  implements java.io.Serializable {


     private int codJogador;
     private int codPartida;

    public JogamId() {
    }

    public JogamId(int codJogador, int codPartida) {
       this.codJogador = codJogador;
       this.codPartida = codPartida;
    }
   
    public int getCodJogador() {
        return this.codJogador;
    }
    
    public void setCodJogador(int codJogador) {
        this.codJogador = codJogador;
    }
    public int getCodPartida() {
        return this.codPartida;
    }
    
    public void setCodPartida(int codPartida) {
        this.codPartida = codPartida;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JogamId) ) return false;
		 JogamId castOther = ( JogamId ) other; 
         
		 return (this.getCodJogador()==castOther.getCodJogador())
 && (this.getCodPartida()==castOther.getCodPartida());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodJogador();
         result = 37 * result + this.getCodPartida();
         return result;
   }   


}


