package br.uff.es2.war.entity;
// Generated 05/09/2014 12:02:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Mundo generated by hbm2java
 */
public class Mundo  implements java.io.Serializable {


     private int codMundo;
     private String nome;
     private Set continentes = new HashSet(0);

    public Mundo() {
    }

	
    public Mundo(int codMundo) {
        this.codMundo = codMundo;
    }
    public Mundo(int codMundo, String nome, Set continentes) {
       this.codMundo = codMundo;
       this.nome = nome;
       this.continentes = continentes;
    }
   
    public int getCodMundo() {
        return this.codMundo;
    }
    
    public void setCodMundo(int codMundo) {
        this.codMundo = codMundo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getContinentes() {
        return this.continentes;
    }
    
    public void setContinentes(Set continentes) {
        this.continentes = continentes;
    }




}


