package br.uff.es2.war.entity;
// Generated 05/09/2014 12:02:41 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private int codPartida;
     private Jogador jogador;
     private Date dataInicio;
     private Date dataFim;
     private Integer troca;
     private int qtdJogador;
     private int rodada;
     private Set jogams = new HashSet(0);
     private Historico historico;

    public Partida() {
    }

	
    public Partida(int codPartida, Date dataInicio, int qtdJogador, int rodada) {
        this.codPartida = codPartida;
        this.dataInicio = dataInicio;
        this.qtdJogador = qtdJogador;
        this.rodada = rodada;
    }
    public Partida(int codPartida, Jogador jogador, Date dataInicio, Date dataFim, Integer troca, int qtdJogador, int rodada, Set jogams, Historico historico) {
       this.codPartida = codPartida;
       this.jogador = jogador;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.troca = troca;
       this.qtdJogador = qtdJogador;
       this.rodada = rodada;
       this.jogams = jogams;
       this.historico = historico;
    }
   
    public int getCodPartida() {
        return this.codPartida;
    }
    
    public void setCodPartida(int codPartida) {
        this.codPartida = codPartida;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }
    public Integer getTroca() {
        return this.troca;
    }
    
    public void setTroca(Integer troca) {
        this.troca = troca;
    }
    public int getQtdJogador() {
        return this.qtdJogador;
    }
    
    public void setQtdJogador(int qtdJogador) {
        this.qtdJogador = qtdJogador;
    }
    public int getRodada() {
        return this.rodada;
    }
    
    public void setRodada(int rodada) {
        this.rodada = rodada;
    }
    public Set getJogams() {
        return this.jogams;
    }
    
    public void setJogams(Set jogams) {
        this.jogams = jogams;
    }
    public Historico getHistorico() {
        return this.historico;
    }
    
    public void setHistorico(Historico historico) {
        this.historico = historico;
    }




}


