package malote;
// Generated 03/09/2014 12:14:03 by Hibernate Tools 3.6.0



/**
 * Jogadorcarta generated by hbm2java
 */
public class Jogadorcarta  implements java.io.Serializable {


     private JogadorcartaId id;
     private Jogam jogam;
     private Carta carta;
     private int turno;

    public Jogadorcarta() {
    }

    public Jogadorcarta(JogadorcartaId id, Jogam jogam, Carta carta, int turno) {
       this.id = id;
       this.jogam = jogam;
       this.carta = carta;
       this.turno = turno;
    }
   
    public JogadorcartaId getId() {
        return this.id;
    }
    
    public void setId(JogadorcartaId id) {
        this.id = id;
    }
    public Jogam getJogam() {
        return this.jogam;
    }
    
    public void setJogam(Jogam jogam) {
        this.jogam = jogam;
    }
    public Carta getCarta() {
        return this.carta;
    }
    
    public void setCarta(Carta carta) {
        this.carta = carta;
    }
    public int getTurno() {
        return this.turno;
    }
    
    public void setTurno(int turno) {
        this.turno = turno;
    }




}


