package malote;
// Generated 03/09/2014 12:14:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Jogam generated by hbm2java
 */
public class Jogam  implements java.io.Serializable {


     private JogamId id;
     private Jogador jogador;
     private Partida partida;
     private Objetivo objetivo;
     private Cor cor;
     private Set jogadorcartas = new HashSet(0);
     private Set ocupacaos = new HashSet(0);

    public Jogam() {
    }

	
    public Jogam(JogamId id, Jogador jogador, Partida partida, Objetivo objetivo, Cor cor) {
        this.id = id;
        this.jogador = jogador;
        this.partida = partida;
        this.objetivo = objetivo;
        this.cor = cor;
    }
    public Jogam(JogamId id, Jogador jogador, Partida partida, Objetivo objetivo, Cor cor, Set jogadorcartas, Set ocupacaos) {
       this.id = id;
       this.jogador = jogador;
       this.partida = partida;
       this.objetivo = objetivo;
       this.cor = cor;
       this.jogadorcartas = jogadorcartas;
       this.ocupacaos = ocupacaos;
    }
   
    public JogamId getId() {
        return this.id;
    }
    
    public void setId(JogamId id) {
        this.id = id;
    }
    public Jogador getJogador() {
        return this.jogador;
    }
    
    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public Objetivo getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(Objetivo objetivo) {
        this.objetivo = objetivo;
    }
    public Cor getCor() {
        return this.cor;
    }
    
    public void setCor(Cor cor) {
        this.cor = cor;
    }
    public Set getJogadorcartas() {
        return this.jogadorcartas;
    }
    
    public void setJogadorcartas(Set jogadorcartas) {
        this.jogadorcartas = jogadorcartas;
    }
    public Set getOcupacaos() {
        return this.ocupacaos;
    }
    
    public void setOcupacaos(Set ocupacaos) {
        this.ocupacaos = ocupacaos;
    }




}


