package malote;
// Generated 03/09/2014 12:14:03 by Hibernate Tools 3.6.0



/**
 * Objderjogador generated by hbm2java
 */
public class Objderjogador  implements java.io.Serializable {


     private ObjderjogadorId id;
     private Objetivo objetivoByCodObjetivo;
     private Objetivo objetivoByCodObjetivoSec;
     private Cor cor;

    public Objderjogador() {
    }

    public Objderjogador(ObjderjogadorId id, Objetivo objetivoByCodObjetivo, Objetivo objetivoByCodObjetivoSec, Cor cor) {
       this.id = id;
       this.objetivoByCodObjetivo = objetivoByCodObjetivo;
       this.objetivoByCodObjetivoSec = objetivoByCodObjetivoSec;
       this.cor = cor;
    }
   
    public ObjderjogadorId getId() {
        return this.id;
    }
    
    public void setId(ObjderjogadorId id) {
        this.id = id;
    }
    public Objetivo getObjetivoByCodObjetivo() {
        return this.objetivoByCodObjetivo;
    }
    
    public void setObjetivoByCodObjetivo(Objetivo objetivoByCodObjetivo) {
        this.objetivoByCodObjetivo = objetivoByCodObjetivo;
    }
    public Objetivo getObjetivoByCodObjetivoSec() {
        return this.objetivoByCodObjetivoSec;
    }
    
    public void setObjetivoByCodObjetivoSec(Objetivo objetivoByCodObjetivoSec) {
        this.objetivoByCodObjetivoSec = objetivoByCodObjetivoSec;
    }
    public Cor getCor() {
        return this.cor;
    }
    
    public void setCor(Cor cor) {
        this.cor = cor;
    }




}


