package malote;
// Generated 03/09/2014 12:14:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Objetivo generated by hbm2java
 */
public class Objetivo  implements java.io.Serializable {


     private Integer codObjetivo;
     private String descricao;
     private Set jogams = new HashSet(0);
     private Set objderjogadorsForCodObjetivoSec = new HashSet(0);
     private Objterritorio objterritorio;
     private Objconqcont objconqcont;
     private Set historicos = new HashSet(0);
     private Set objderjogadorsForCodObjetivo = new HashSet(0);

    public Objetivo() {
    }

	
    public Objetivo(String descricao) {
        this.descricao = descricao;
    }
    public Objetivo(String descricao, Set jogams, Set objderjogadorsForCodObjetivoSec, Objterritorio objterritorio, Objconqcont objconqcont, Set historicos, Set objderjogadorsForCodObjetivo) {
       this.descricao = descricao;
       this.jogams = jogams;
       this.objderjogadorsForCodObjetivoSec = objderjogadorsForCodObjetivoSec;
       this.objterritorio = objterritorio;
       this.objconqcont = objconqcont;
       this.historicos = historicos;
       this.objderjogadorsForCodObjetivo = objderjogadorsForCodObjetivo;
    }
   
    public Integer getCodObjetivo() {
        return this.codObjetivo;
    }
    
    public void setCodObjetivo(Integer codObjetivo) {
        this.codObjetivo = codObjetivo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getJogams() {
        return this.jogams;
    }
    
    public void setJogams(Set jogams) {
        this.jogams = jogams;
    }
    public Set getObjderjogadorsForCodObjetivoSec() {
        return this.objderjogadorsForCodObjetivoSec;
    }
    
    public void setObjderjogadorsForCodObjetivoSec(Set objderjogadorsForCodObjetivoSec) {
        this.objderjogadorsForCodObjetivoSec = objderjogadorsForCodObjetivoSec;
    }
    public Objterritorio getObjterritorio() {
        return this.objterritorio;
    }
    
    public void setObjterritorio(Objterritorio objterritorio) {
        this.objterritorio = objterritorio;
    }
    public Objconqcont getObjconqcont() {
        return this.objconqcont;
    }
    
    public void setObjconqcont(Objconqcont objconqcont) {
        this.objconqcont = objconqcont;
    }
    public Set getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Set historicos) {
        this.historicos = historicos;
    }
    public Set getObjderjogadorsForCodObjetivo() {
        return this.objderjogadorsForCodObjetivo;
    }
    
    public void setObjderjogadorsForCodObjetivo(Set objderjogadorsForCodObjetivo) {
        this.objderjogadorsForCodObjetivo = objderjogadorsForCodObjetivo;
    }




}


