package malote;
// Generated 03/09/2014 12:14:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Territorio generated by hbm2java
 */
public class Territorio  implements java.io.Serializable {


     private int codTerritorio;
     private Continente continente;
     private String nome;
     private Set cartas = new HashSet(0);
     private Set territoriosForCodLocal = new HashSet(0);
     private Set ocupacaos = new HashSet(0);
     private Set territoriosForCodVizinho = new HashSet(0);

    public Territorio() {
    }

	
    public Territorio(int codTerritorio, Continente continente, String nome) {
        this.codTerritorio = codTerritorio;
        this.continente = continente;
        this.nome = nome;
    }
    public Territorio(int codTerritorio, Continente continente, String nome, Set cartas, Set territoriosForCodLocal, Set ocupacaos, Set territoriosForCodVizinho) {
       this.codTerritorio = codTerritorio;
       this.continente = continente;
       this.nome = nome;
       this.cartas = cartas;
       this.territoriosForCodLocal = territoriosForCodLocal;
       this.ocupacaos = ocupacaos;
       this.territoriosForCodVizinho = territoriosForCodVizinho;
    }
   
    public int getCodTerritorio() {
        return this.codTerritorio;
    }
    
    public void setCodTerritorio(int codTerritorio) {
        this.codTerritorio = codTerritorio;
    }
    public Continente getContinente() {
        return this.continente;
    }
    
    public void setContinente(Continente continente) {
        this.continente = continente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getCartas() {
        return this.cartas;
    }
    
    public void setCartas(Set cartas) {
        this.cartas = cartas;
    }
    public Set getTerritoriosForCodLocal() {
        return this.territoriosForCodLocal;
    }
    
    public void setTerritoriosForCodLocal(Set territoriosForCodLocal) {
        this.territoriosForCodLocal = territoriosForCodLocal;
    }
    public Set getOcupacaos() {
        return this.ocupacaos;
    }
    
    public void setOcupacaos(Set ocupacaos) {
        this.ocupacaos = ocupacaos;
    }
    public Set getTerritoriosForCodVizinho() {
        return this.territoriosForCodVizinho;
    }
    
    public void setTerritoriosForCodVizinho(Set territoriosForCodVizinho) {
        this.territoriosForCodVizinho = territoriosForCodVizinho;
    }




}


