package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Carta generated by hbm2java
 */
public class Carta  implements java.io.Serializable {


     private Integer codCarta;
     private Territorio territorio;
     private Integer forma;
     private Set jogadorcartas = new HashSet(0);

    public Carta() {
    }

    public Carta(Territorio territorio, Integer forma, Set jogadorcartas) {
       this.territorio = territorio;
       this.forma = forma;
       this.jogadorcartas = jogadorcartas;
    }
   
    public Integer getCodCarta() {
        return this.codCarta;
    }
    
    public void setCodCarta(Integer codCarta) {
        this.codCarta = codCarta;
    }
    public Territorio getTerritorio() {
        return this.territorio;
    }
    
    public void setTerritorio(Territorio territorio) {
        this.territorio = territorio;
    }
    public Integer getForma() {
        return this.forma;
    }
    
    public void setForma(Integer forma) {
        this.forma = forma;
    }
    public Set getJogadorcartas() {
        return this.jogadorcartas;
    }
    
    public void setJogadorcartas(Set jogadorcartas) {
        this.jogadorcartas = jogadorcartas;
    }




}


