package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Continente generated by hbm2java
 */
public class Continente  implements java.io.Serializable {


     private Integer codContinente;
     private String nome;
     private Set objconqconts = new HashSet(0);
     private Set territorios = new HashSet(0);

    public Continente() {
    }

	
    public Continente(String nome) {
        this.nome = nome;
    }
    public Continente(String nome, Set objconqconts, Set territorios) {
       this.nome = nome;
       this.objconqconts = objconqconts;
       this.territorios = territorios;
    }
   
    public Integer getCodContinente() {
        return this.codContinente;
    }
    
    public void setCodContinente(Integer codContinente) {
        this.codContinente = codContinente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getObjconqconts() {
        return this.objconqconts;
    }
    
    public void setObjconqconts(Set objconqconts) {
        this.objconqconts = objconqconts;
    }
    public Set getTerritorios() {
        return this.territorios;
    }
    
    public void setTerritorios(Set territorios) {
        this.territorios = territorios;
    }




}


