package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cor generated by hbm2java
 */
public class Cor  implements java.io.Serializable {


     private Integer codCor;
     private String nome;
     private Set objderjogadors = new HashSet(0);
     private Set jogams = new HashSet(0);

    public Cor() {
    }

	
    public Cor(String nome) {
        this.nome = nome;
    }
    public Cor(String nome, Set objderjogadors, Set jogams) {
       this.nome = nome;
       this.objderjogadors = objderjogadors;
       this.jogams = jogams;
    }
   
    public Integer getCodCor() {
        return this.codCor;
    }
    
    public void setCodCor(Integer codCor) {
        this.codCor = codCor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getObjderjogadors() {
        return this.objderjogadors;
    }
    
    public void setObjderjogadors(Set objderjogadors) {
        this.objderjogadors = objderjogadors;
    }
    public Set getJogams() {
        return this.jogams;
    }
    
    public void setJogams(Set jogams) {
        this.jogams = jogams;
    }




}


