package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Objconqcont generated by hbm2java
 */
public class Objconqcont  implements java.io.Serializable {


     private int codObjetivo;
     private Objetivo objetivo;
     private Integer continentesExtras;
     private Set continentes = new HashSet(0);

    public Objconqcont() {
    }

	
    public Objconqcont(Objetivo objetivo) {
        this.objetivo = objetivo;
    }
    public Objconqcont(Objetivo objetivo, Integer continentesExtras, Set continentes) {
       this.objetivo = objetivo;
       this.continentesExtras = continentesExtras;
       this.continentes = continentes;
    }
   
    public int getCodObjetivo() {
        return this.codObjetivo;
    }
    
    public void setCodObjetivo(int codObjetivo) {
        this.codObjetivo = codObjetivo;
    }
    public Objetivo getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(Objetivo objetivo) {
        this.objetivo = objetivo;
    }
    public Integer getContinentesExtras() {
        return this.continentesExtras;
    }
    
    public void setContinentesExtras(Integer continentesExtras) {
        this.continentesExtras = continentesExtras;
    }
    public Set getContinentes() {
        return this.continentes;
    }
    
    public void setContinentes(Set continentes) {
        this.continentes = continentes;
    }




}


