package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0



/**
 * ObjderjogadorId generated by hbm2java
 */
public class ObjderjogadorId  implements java.io.Serializable {


     private int codObjetivoSec;
     private int codObjetivo;
     private int codCor;

    public ObjderjogadorId() {
    }

    public ObjderjogadorId(int codObjetivoSec, int codObjetivo, int codCor) {
       this.codObjetivoSec = codObjetivoSec;
       this.codObjetivo = codObjetivo;
       this.codCor = codCor;
    }
   
    public int getCodObjetivoSec() {
        return this.codObjetivoSec;
    }
    
    public void setCodObjetivoSec(int codObjetivoSec) {
        this.codObjetivoSec = codObjetivoSec;
    }
    public int getCodObjetivo() {
        return this.codObjetivo;
    }
    
    public void setCodObjetivo(int codObjetivo) {
        this.codObjetivo = codObjetivo;
    }
    public int getCodCor() {
        return this.codCor;
    }
    
    public void setCodCor(int codCor) {
        this.codCor = codCor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObjderjogadorId) ) return false;
		 ObjderjogadorId castOther = ( ObjderjogadorId ) other; 
         
		 return (this.getCodObjetivoSec()==castOther.getCodObjetivoSec())
 && (this.getCodObjetivo()==castOther.getCodObjetivo())
 && (this.getCodCor()==castOther.getCodCor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodObjetivoSec();
         result = 37 * result + this.getCodObjetivo();
         result = 37 * result + this.getCodCor();
         return result;
   }   


}


