package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0



/**
 * Objterritorio generated by hbm2java
 */
public class Objterritorio  implements java.io.Serializable {


     private int codObjetivo;
     private Objetivo objetivo;
     private int qtdTerritorio;
     private Integer minExercito;

    public Objterritorio() {
    }

	
    public Objterritorio(Objetivo objetivo, int qtdTerritorio) {
        this.objetivo = objetivo;
        this.qtdTerritorio = qtdTerritorio;
    }
    public Objterritorio(Objetivo objetivo, int qtdTerritorio, Integer minExercito) {
       this.objetivo = objetivo;
       this.qtdTerritorio = qtdTerritorio;
       this.minExercito = minExercito;
    }
   
    public int getCodObjetivo() {
        return this.codObjetivo;
    }
    
    public void setCodObjetivo(int codObjetivo) {
        this.codObjetivo = codObjetivo;
    }
    public Objetivo getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(Objetivo objetivo) {
        this.objetivo = objetivo;
    }
    public int getQtdTerritorio() {
        return this.qtdTerritorio;
    }
    
    public void setQtdTerritorio(int qtdTerritorio) {
        this.qtdTerritorio = qtdTerritorio;
    }
    public Integer getMinExercito() {
        return this.minExercito;
    }
    
    public void setMinExercito(Integer minExercito) {
        this.minExercito = minExercito;
    }




}


