package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0



/**
 * Ocupacao generated by hbm2java
 */
public class Ocupacao  implements java.io.Serializable {


     private OcupacaoId id;
     private Jogam jogam;
     private Territorio territorio;
     private Integer turno;
     private Integer qntExercito;

    public Ocupacao() {
    }

	
    public Ocupacao(OcupacaoId id, Jogam jogam, Territorio territorio) {
        this.id = id;
        this.jogam = jogam;
        this.territorio = territorio;
    }
    public Ocupacao(OcupacaoId id, Jogam jogam, Territorio territorio, Integer turno, Integer qntExercito) {
       this.id = id;
       this.jogam = jogam;
       this.territorio = territorio;
       this.turno = turno;
       this.qntExercito = qntExercito;
    }
   
    public OcupacaoId getId() {
        return this.id;
    }
    
    public void setId(OcupacaoId id) {
        this.id = id;
    }
    public Jogam getJogam() {
        return this.jogam;
    }
    
    public void setJogam(Jogam jogam) {
        this.jogam = jogam;
    }
    public Territorio getTerritorio() {
        return this.territorio;
    }
    
    public void setTerritorio(Territorio territorio) {
        this.territorio = territorio;
    }
    public Integer getTurno() {
        return this.turno;
    }
    
    public void setTurno(Integer turno) {
        this.turno = turno;
    }
    public Integer getQntExercito() {
        return this.qntExercito;
    }
    
    public void setQntExercito(Integer qntExercito) {
        this.qntExercito = qntExercito;
    }




}


