package model;
// Generated 04/09/2014 19:22:09 by Hibernate Tools 3.6.0



/**
 * OcupacaoId generated by hbm2java
 */
public class OcupacaoId  implements java.io.Serializable {


     private int codTerritorio;
     private int codJogador;
     private int codPartida;

    public OcupacaoId() {
    }

    public OcupacaoId(int codTerritorio, int codJogador, int codPartida) {
       this.codTerritorio = codTerritorio;
       this.codJogador = codJogador;
       this.codPartida = codPartida;
    }
   
    public int getCodTerritorio() {
        return this.codTerritorio;
    }
    
    public void setCodTerritorio(int codTerritorio) {
        this.codTerritorio = codTerritorio;
    }
    public int getCodJogador() {
        return this.codJogador;
    }
    
    public void setCodJogador(int codJogador) {
        this.codJogador = codJogador;
    }
    public int getCodPartida() {
        return this.codPartida;
    }
    
    public void setCodPartida(int codPartida) {
        this.codPartida = codPartida;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcupacaoId) ) return false;
		 OcupacaoId castOther = ( OcupacaoId ) other; 
         
		 return (this.getCodTerritorio()==castOther.getCodTerritorio())
 && (this.getCodJogador()==castOther.getCodJogador())
 && (this.getCodPartida()==castOther.getCodPartida());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodTerritorio();
         result = 37 * result + this.getCodJogador();
         result = 37 * result + this.getCodPartida();
         return result;
   }   


}


